export interface User {
  id: number,
  username: string,
  fullname: string,
  email: any,
  dien_thoai: any,
  remember_token: any,
  created_at: any,
  updated_at: any,
  is_active: string,
  user_type: string,
  user_group: string,
  ma_cskcb: any,
  ma_tinh: any,
  nha_thau_id: any,
  ngay_sinh: any,
  trinh_do: any,
  masobhxh: any,
  vi_tri: any,
  change_password: string,
  access_token: string,
  scopes: [],
  is_delete: any,
  is_arv: any,
  is_lao: any,

  // [key: string]: any;
}
